version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  celery:
    restart: always
    build: ./
    command: celery -A fruit  worker -Q queue1 -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - fruit_postgres_data:/var/lib/postgresql/fruit_data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass12345
      - POSTGRES_DB=fruit
  redis:
    image: "redis:alpine"
  celery-beat:
    build: ./
    command: celery -A fruit beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  fruit_postgres_data: