# Generated by Django 3.2.9 on 2021-11-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    def create_products(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        product = apps.get_model('fruit_admin', 'Product')
        product_count = apps.get_model('fruit_admin', 'ProductCount')
        product_object = product.objects.create(name='яблоки', price=4)
        product_count.objects.create(product=product_object, quantity=0)
        product_object = product.objects.create(name='бананы', price=1)
        product_count.objects.create(product=product_object, quantity=0)
        product_object = product.objects.create(name='ананасы', price=3)
        product_count.objects.create(product=product_object, quantity=0)
        product_object = product.objects.create(name='персики', price=2)
        product_count.objects.create(product=product_object, quantity=0)
    dependencies = [
        ('fruit_admin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_products),
    ]
