# Generated by Django 3.2.9 on 2021-11-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    def create_cash(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        product = apps.get_model('fruit_admin', 'Cash')
        product.objects.create(sum=0.0)
    dependencies = [
        ('fruit_admin', '0003_cash'),
    ]

    operations = [
        migrations.RunPython(create_cash),
    ]
