# Generated by Django 3.2.9 on 2021-11-24 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_admin', '0004_auto_20211122_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 24, 12, 44, 39, 848085)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], default='SUCCESS', max_length=30),
        ),
    ]
