# Generated by Django 3.2.9 on 2021-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_admin', '0005_auto_20211124_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Продажа', 'Продажа')], max_length=20),
        ),
    ]
